const offer = {
  //copy and paste the offer generated by the serverpeerA
};

const rc = new RTCPeerConnection();

rc.onicecandidate = (e) =>
  console.log(
    "New ICE candidate!!adding ot to sdp" + JSON.stringify(rc.localDescription)
  );

rc.ondatachannel = (e) => {
  rc.dc = e.channel;
  rc.dc.onmessage = (e) => console.log("New message from support" + e.data);
  rc.dc.onopen = (e) => console.log("Connection from client is open");
};

rc.setRemoteDescription(offer).then((a) => console.log("offer set"));

rc.createAnswer()
  .then((a) => rc.setLocalDescription(a))
  .then((a) => console.log("answer created"));
//answer/ice candidates will be generated wwhich the last one you have to copy and paste it on the serverpeerA
